[package]
name = "noxy"
version = "0.0.0"
edition = "2021"
authors = ["nop noplab90@gmail.com"]
description = "WIP"
license = "MIT"

[dependencies]
env_logger = "0.11"
log = "0.4"
wgpu = "25.0"
winit = "0.30"
anyhow = "1"
pollster = "0.4.0"
bytemuck = "1.23.0"
glam = "0.30.3"
